import { describe, expect, it } from "vitest";

import * as schemas from "./index.js";
import type {
  ArtifactResult,
  ArtifactKind,
  ArtifactStatus,
  Claim,
  ClaimVerdict,
  ClaimVerdictStatus,
  CommandPlan,
  CommandResult,
  CommandStatus,
  ConfigArtifact,
  ConfigCommand,
  ConfigGit,
  ConfigReporting,
  ConfigSafety,
  DecisionArtifactSummary,
  DecisionClaimSummary,
  DecisionCommandSummary,
  DecisionRiskSummary,
  DecisionSummary,
  EvidenceId,
  EvidenceKind,
  FinalVerdict,
  GitEvidence,
  NormalizedConfig,
  PipelineError,
  ReportOutputPaths,
  RepoProfile,
  RiskCategory,
  RiskFinding,
  RiskScoreSeverity,
  RiskScoreSummary,
  RiskSeverity,
  SchemaVersion,
  ToolStatus,
  VerificationReport,
  VerificationMode,
  VerificationRequest,
} from "./index.js";

const inferredTypeProof: readonly unknown[] = [
  null as unknown as EvidenceId,
  null as unknown as FinalVerdict,
  null as unknown as ToolStatus,
  null as unknown as ClaimVerdictStatus,
  null as unknown as RiskSeverity,
  null as unknown as RiskCategory,
  null as unknown as EvidenceKind,
  null as unknown as ArtifactKind,
  null as unknown as ArtifactStatus,
  null as unknown as CommandStatus,
  null as unknown as VerificationMode,
  null as unknown as VerificationRequest,
  null as unknown as ConfigCommand,
  null as unknown as ConfigArtifact,
  null as unknown as ConfigSafety,
  null as unknown as ConfigReporting,
  null as unknown as ConfigGit,
  null as unknown as DecisionArtifactSummary,
  null as unknown as DecisionClaimSummary,
  null as unknown as DecisionCommandSummary,
  null as unknown as DecisionRiskSummary,
  null as unknown as DecisionSummary,
  null as unknown as NormalizedConfig,
  null as unknown as RepoProfile,
  null as unknown as GitEvidence,
  null as unknown as CommandPlan,
  null as unknown as CommandResult,
  null as unknown as ArtifactResult,
  null as unknown as Claim,
  null as unknown as ClaimVerdict,
  null as unknown as RiskFinding,
  null as unknown as RiskScoreSummary,
  null as unknown as RiskScoreSeverity,
  null as unknown as ReportOutputPaths,
  null as unknown as VerificationReport,
  null as unknown as PipelineError,
  null as unknown as SchemaVersion,
];

const expectedPublicApiExports = [
  "ArtifactKindSchema",
  "ArtifactResultSchema",
  "ArtifactStatusSchema",
  "ClaimSchema",
  "ClaimVerdictSchema",
  "ClaimVerdictStatusSchema",
  "CommandPlanSchema",
  "CommandResultSchema",
  "CommandStatusSchema",
  "ConfigArtifactSchema",
  "ConfigCommandSchema",
  "ConfigGitSchema",
  "ConfigReportingSchema",
  "ConfigSafetySchema",
  "DecisionArtifactSummarySchema",
  "DecisionClaimSummarySchema",
  "DecisionCommandSummarySchema",
  "DecisionRiskSummarySchema",
  "DecisionSummarySchema",
  "EvidenceIdSchema",
  "EvidenceKindSchema",
  "FinalVerdictSchema",
  "GitEvidenceSchema",
  "NonEmptyStringSchema",
  "NonNegativeIntegerSchema",
  "NormalizedConfigSchema",
  "PipelineErrorSchema",
  "PositiveIntegerSchema",
  "RepoProfileSchema",
  "ReportOutputPathsSchema",
  "RiskCategorySchema",
  "RiskFindingSchema",
  "RiskScoreSeveritySchema",
  "RiskScoreSummarySchema",
  "RiskSeveritySchema",
  "SchemaVersionSchema",
  "ToolStatusSchema",
  "UnknownRecordSchema",
  "VerificationModeSchema",
  "VerificationReportSchema",
  "VerificationRequestSchema",
  "artifactKinds",
  "artifactStatuses",
  "claimVerdictStatuses",
  "commandStatuses",
  "evidenceKinds",
  "finalVerdicts",
  "maxConfigArtifacts",
  "maxConfigCommands",
  "riskCategories",
  "riskScoreSeverities",
  "riskSeverities",
  "sampleDemoBlockedReport",
  "sampleNormalizedConfig",
  "sampleRiskFinding",
  "sampleRiskScoreSummary",
  "sampleSafeReport",
  "schemaVersion",
  "toolStatuses",
  "verificationModes",
] as const;

describe("@agentforge-qa/schemas exports", () => {
  it("pins the complete intended runtime public API", () => {
    expect(Object.keys(schemas).sort()).toEqual(
      [...expectedPublicApiExports].sort(),
    );
  });

  it("exports all required inferred types at compile time", () => {
    expect(inferredTypeProof).toHaveLength(37);
  });
});
